### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by 0Navis0** [GL33P-0R4NG3/oreganized#119]
```
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=0,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=1,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=3,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=2,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=6,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=12,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=4,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=5,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=11,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=5,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=6,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=10,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=4,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=8,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=7,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=10,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=11,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=9,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=9,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=3,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=1,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=2,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=13,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=14,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=14,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=7,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=15,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=12,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=13,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=0,moving=false'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=8,moving=true'
[07:07:54] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'oreganized:blockstates/molten_lead.json' missing model for variant: 'oreganized:molten_lead#level=15,moving=true'
```

**Comment by Hypsellis** [comment]
Also these error keeps flooding the log.
https://pastebin.com/iWekVK1h

**Comment by 0Navis0** [comment]
```
[07:08:13] [Worker-Main-5/ERROR]: Couldn't load tag [nethersdelight:hoglin_loin (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:hoglin_sirloin (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:strider_slice (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:ground_strider (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:hoglin_ear (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:warped_moldy_meat (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:grilled_strider (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:strider_moss_stew (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:plate_of_stuffed_hoglin_snout (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:plate_of_stuffed_hoglin_ham (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:plate_of_stuffed_hoglin_roast (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:propelpearl (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:nether_skewer (from Oreganized 1.19.2-2.0.2.jar), nethersdelight:magma_gelatin (from Oreganized 1.19.2-2.0.2.jar)] as it is missing following references: nethersdelight:hoglin_loin (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:hoglin_sirloin (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:strider_slice (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:ground_strider (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:hoglin_ear (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:warped_moldy_meat (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:grilled_strider (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:strider_moss_stew (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:plate_of_stuffed_hoglin_snout (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:plate_of_stuffed_hoglin_ham (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:plate_of_stuffed_hoglin_roast (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:propelpearl (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:nether_skewer (from Oreganized 1.19.2-2.0.2.jar), 
	nethersdelight:magma_gelatin (from Oreganized 1.19.2-2.0.2.jar)

[07:08:14] [Render thread/ERROR]: Parsing error loading recipe oreganized:quark/boltarang
com.google.gson.JsonSyntaxException: Unknown item 'oreganized:boltarang'
	at net.minecraftforge.common.crafting.CraftingHelper.getItem(CraftingHelper.java:154) ~[forge-1.19.2-43.2.4-universal.jar%23264!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:180) ~[forge-1.19.2-43.2.4-universal.jar%23264!/:?]
	at net.minecraft.world.item.crafting.ShapedRecipe.m_151274_(ShapedRecipe.java:269) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.world.item.crafting.UpgradeRecipe$Serializer.m_6729_(UpgradeRecipe.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.world.item.crafting.UpgradeRecipe$Serializer.m_6729_(UpgradeRecipe.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.19.2-43.2.4-universal.jar%23264!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:171) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232896_(CreateWorldScreen.java:124) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.m_233213_(WorldSelectionList.java:147) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.<init>(WorldSelectionList.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_7856_(SelectWorldScreen.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.Screen.m_232761_(Screen.java:421) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:411) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:974) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_96775_(TitleScreen.java:159) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_6375_(TitleScreen.java:368) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by 0Navis0** [comment]
Also these errors keeps flooding the log.
https://pastebin.com/ER89MHSa
