### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by carnivorchild** [GL33P-0R4NG3/oreganized#42]
---- Minecraft Crash Report ----
// Don't do that.

Time: 25/04/21 19:29
Description: Unexpected error

java.lang.IllegalStateException: Lock is no longer valid
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237301_i_(SaveFormat.java:296) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237298_f_(SaveFormat.java:360) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_184109_z(MinecraftServer.java:770) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_184106_y(MinecraftServer.java:764) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/589610983.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237301_i_(SaveFormat.java:296) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237298_f_(SaveFormat.java:360) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_184109_z(MinecraftServer.java:770) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_184106_y(MinecraftServer.java:764) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Blackwyvern5178'/182, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 841, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/589610983.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2008658608 bytes (1915 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.4.88.jar                           |Just Enough Items             |jei                           |7.6.4.88            |DONE      |NOSIGNATURE
		Druidcraft-1.16.5-0.4.52.jar                      |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |NOSIGNATURE
		AttributeFix-1.16.5-10.1.2.jar                    |AttributeFix                  |attributefix                  |10.1.2              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.1.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.1               |DONE      |NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |DONE      |NOSIGNATURE
		glassential-forge-1.16.5-1.1.6.jar                |Glassential                   |glassential                   |1.1.6               |DONE      |NOSIGNATURE
		fight-stick-1.16.4-1.0.0.jar                      |Fight Stick                   |fight_stick                   |1.0.0               |DONE      |NOSIGNATURE
		NeverNeededOrWanted-1.16.5-1.0.9a.jar             |Never Needed Or Wanted        |nnow                          |1.16.5-1.0.9a       |DONE      |NOSIGNATURE
		slimierslimes-1.16.5-1.1.2.jar                    |Slimier Slimes                |slimier-slimes                |1.16.5-1.1.2        |DONE      |NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |NOSIGNATURE
		dankstorage-3.16.jar                              |Dank Storage                  |dankstorage                   |3.16                |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		alexsmobs-1.9.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.9.1               |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.7.jar                       |Bookshelf                     |bookshelf                     |10.0.7              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyPots-1.16.5-7.0.17.jar                      |BotanyPots                    |botanypots                    |7.0.17              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		reliquary-1.16.5-1.3.5.1096.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1096   |DONE      |NOSIGNATURE
		guardvillagers-1.16.5.1.2.3.jar                   |Guard Villagers               |guardvillagers                |1.2.3               |DONE      |NOSIGNATURE
		TinyMobFarm-1.16.4-1.1.1.jar                      |Tiny Mob Farm                 |tinymobfarm                   |1.1.1               |DONE      |NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |DONE      |NOSIGNATURE
		wikizoomer-1.0.3-1.16.4.jar                       |Wiki Zoomer                   |wikizoomer                    |1.0.3               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		supplementaries-1.16.5-0.12.1.jar                 |Supplementaries               |supplementaries               |1.16.5-0.12.1       |DONE      |NOSIGNATURE
		Upgraded+Netherite+1.16.4+-+1.8.1.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		BotanyTrees-1.16.5-3.0.4.jar                      |BotanyTrees                   |botanytrees                   |3.0.4               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		oreganized-1.16.4-0.4.4-beta.jar                  |Oreganized Mod                |oreganized                    |1.16.4-0.4.4-beta   |DONE      |NOSIGNATURE
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |DONE      |NOSIGNATURE
		playerex-1.1.7.5-1.16.4.jar                       |Player Ex                     |playerex                      |1.1.7.5             |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		Mantle-1.16.5-1.6.92.jar                          |Mantle                        |mantle                        |1.6.92              |DONE      |NOSIGNATURE
		Inspirations-1.16.5-1.2.2.jar                     |Inspirations                  |inspirations                  |1.2.2               |DONE      |NOSIGNATURE
		improved_genetics-0.7.1.jar                       |Improved Genetics             |improved_genetics             |v0.7.1              |DONE      |NOSIGNATURE
		extlights-3.3.jar                                 |Extended Lights               |extlights                     |3.3                 |DONE      |NOSIGNATURE
		polymorph-forge-1.16.5-0.24.jar                   |Polymorph                     |polymorph                     |1.16.5-0.24         |DONE      |NOSIGNATURE
		corail_recycler-1.16-5.0.0.jar                    |Corail Recycler               |corail_recycler               |5.0.0               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-310.jar                                |Quark                         |quark                         |r2.4-310            |DONE      |NOSIGNATURE
		gk_unbreakable-2.4.jar                            |Unbreakable                   |gk_unbreakable                |2.4                 |DONE      |NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.50.jar                   |Gobber 2                      |gobber2                       |2.3.48              |DONE      |NOSIGNATURE
		buildersaddition-1.16.5-20210421a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210421a    |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.8.jar                        |Vampirism                     |vampirism                     |1.7.8               |DONE      |NOSIGNATURE
		mobcatcher-3.2.jar                                |Mob Catcher                   |mobcatcher                    |3.2                 |DONE      |NOSIGNATURE
		OddWaterMobs[1.16.5]_1.2.5.jar                    |Odd Water Mobs                |oddwatermobs                  |1.2.5               |DONE      |NOSIGNATURE
		The_Undergarden-1.16.5-0.5.1.jar                  |The Undergarden               |undergarden                   |0.5.1               |DONE      |NOSIGNATURE
		byg-1.1.14.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.14              |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.30.jar                  |GeckoLib                      |geckolib3                     |3.0.30              |DONE      |NOSIGNATURE
		lootbagmod-1.16.5-1.6.6.jar                       |Loot Bag Mod                  |lootbagmod                    |1.6.6               |DONE      |NOSIGNATURE
	Crash Report UUID: 76f1520c-571b-4b83-832f-5661b5a8505d
	Launched Version: 1.16.5-forge-36.1.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.72, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, inspirations:config_resources (incompatible), quark:emote_resources (incompatible), file/Cyclops_Monstrous.zip, file/FrostbiteBrimstone.zip, file/Dragon_Eggs_GOT.zip, file/Myrmex_Wild.zip, file/Gorgon_Greek.zip, file/Sirens_Mythical.zip, file/Pixies_Fae.zip, file/Trolls_Friendlier.zip, file/Jicklus+1.16.zip, file/Better+Clear+Water+1.16.2+.zip, file/BSG+-+Combo+-+1.16.zip
	Current Language: Français (France)
	CPU: 2x Intel(R) Pentium(R) CPU G630 @ 2.70GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 12
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.72
	OpenGlRenderer: GeForce GT 710/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by GL33P-0R4NG3** [comment]
I think its just uncompatibility with other mods I dont see some error in our mod also I think I mentioned somwhere that it should not work properly with 1.16.5 and we'll fix this later....
