### ISSUE TITLE
(1.16.5) Server issue

### ISSUE THREAD

**Issue by PhweeDev** [GL33P-0R4NG3/oreganized#90]
[16.04 09:55:25] [Server] DescriptionMod loading error has occurred
[16.04 09:55:25] [Server] java.lang.ExceptionMod Loading has failed
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraft.server.Main.main(Main.java:144) ~[?:?] {re:classloading}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
[16.04 09:55:25] [Server] 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[customjava15.jar:36.{}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:131) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:128) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:112) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[16.04 09:55:25] [Server] ---------------------------------------------------------------------------------------
[16.04 09:55:25] [Server] -- Head --
[16.04 09:55:25] [Server] Threadmain
[16.04 09:55:25] [Server] Stacktrace:
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[customjava15.jar:36.{}
[16.04 09:55:25] [Server] -- MOD oreganized --
[16.04 09:55:25] [Server] Details:
[16.04 09:55:25] [Server] 	Mod Fileoreganized-1.16.4-0.5.1-beta.jar
[16.04 09:55:25] [Server] 	Failure messageOreganized Mod (oreganized) encountered an error during the load_registries event phase
[16.04 09:55:25] [Server] 		java.lang.RuntimeExceptionAttempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
[16.04 09:55:25] [Server] 	Mod Version1.16.4-0.5.1-beta
[16.04 09:55:25] [Server] 	Mod Issue URLhttps://github.com/GL33P-0R4NG3/oreganized/issues/
[16.04 09:55:25] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
[16.04 09:55:25] [Server] Stacktrace:
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[customjava15.jar:36.{}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
[16.04 09:55:25] [Server] 	at me.gleep.oreganized.util.RegistryHandler.lambda$static$17(RegistryHandler.java:133) ~[oreganized:1.16.4-0.5.1-beta] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_3_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:121) ~[forge:36.{re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:252) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:239) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:205) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraft.server.Main.main(Main.java:144) ~[?:?] {re:classloading}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
[16.04 09:55:25] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
[16.04 09:55:25] [Server] 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[customjava15.jar:36.{}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:131) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:128) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:112) [customjava15.jar:?] {}
[16.04 09:55:25] [Server] -- MOD oreganized --
[16.04 09:55:25] [Server] Details:
[16.04 09:55:25] [Server] 	Mod Fileoreganized-1.16.4-0.5.1-beta.jar
[16.04 09:55:25] [Server] 	Failure messageOreganized Mod (oreganized) encountered an error during the error event phase
[16.04 09:55:25] [Server] 		java.lang.NullPointerExceptionRegistry Object not present: oreganized:lightened_iron_stairs
[16.04 09:55:25] [Server] 	Mod Version1.16.4-0.5.1-beta
[16.04 09:55:25] [Server] 	Mod Issue URLhttps://github.com/GL33P-0R4NG3/oreganized/issues/
[16.04 09:55:25] [Server] 	Exception messagejava.lang.NullPointerException: Registry Object not present: oreganized:lightened_iron_stairs
[16.04 09:55:25] [Server] Stacktrace:
[16.04 09:55:25] [Server] 	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
[16.04 09:55:25] [Server] 	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:mixin,re:classloading}
[16.04 09:55:25] [Server] 	at me.gleep.oreganized.util.RegistryHandler.lambda$static$76(RegistryHandler.java:209) ~[oreganized:1.16.4-0.5.1-beta] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[forge:?] {re:classloading}
[16.04 09:55:25] [Server] 	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[forge:?] {re:classloading}

**Comment by GL33P-0R4NG3** [comment]
#76
